[package]
name = "ai-chan"
authors = ["Speykious <speykious@speykious.dev>"]
version = "0.2.0"
edition = "2024"

[dependencies]
chrono = "0.4"
dotenvy = "0.15"
rand = { version = "0.9.2", default-features = false, features = ["std", "thread_rng"] }
serenity = "0.12"
tokio = { version = "1.49", features = [ "rt-multi-thread" ] }
tracing = "0.1"
tracing-subscriber = "0.3"
