[package]
name = "sowiwoquy"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
serenity = "0.12.0"
tokio = { version = "1.35.1", features = [ "rt-multi-thread" ] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
